### ISSUE TITLE
Training uses CPU instead of GPU

### ISSUE THREAD

**Issue by Satsukix** [ddPn08/rvc-webui#15]
836d6ad602a201a4f8e2ca078bf156c32569f4e3 まではGPUで学習ができていたのですが、最新(193d6e718b6be8a6d8efd3346ba7ebe5378ee399)にアップデートしたらCPU使用率が100%になり、GPUが使用されていないようです。
GPUはNvidiaの3060です。
___

Training with GPU worked until 836d6ad602a201a4f8e2ca078bf156c32569f4e3, but with the newest version (193d6e718b6be8a6d8efd3346ba7ebe5378ee399) it seems to train with CPU instead with GPU.
My GPU is Nvidia's 3060.

**Comment by TylorShine** [comment]
わたしも先程最新版を試したところ学習結果が正常ではなく(GPUは使われていました)、
原因を調査すると、 #16 のようだったのでPRを出しています。

もし可能なら、使用したデータセットのファイル数と `models/training/models/<Trainingタブで設定されたModel Name>/0_gt_wavs/<0で埋められたSpeaker ID>/<数値>_n.wav` の <数値> + 1 が同じになっているか確認していただけますか？

**Comment by Satsukix** [comment]
少なめのファイル数で学習を試してみたらGPUが使用されてました。
元のデータセットで再学習してみたところ、GPUが使用されなかったと思っていたのはすべて
前処理の一部だったと判明しました。
前処理が長く（40分ほど）、学習が始まっていたと勘違いをしてしまったようです。
前処理が終わったらGPUが使用されました。

学習のデータセットのファイル数は12449個で、0_gt_wavsの中の<数値>は12448になっていたので多分合っています。

解決したので閉めます、失礼しました。

___

I tried training with a smaller data set and it seems that the GPU was used.
I retrained on the original dataset and it turns out that the process "not using the GPU" was part of the preprocessing.
The preprocessing was long (about 40 minutes), so I thought that training had already started.　When I trained longer the GPU was properly used.

The number of files in the dataset for the training was 12449 and the number in 0_gt_wavs was 12448, so it should be correct.

The problem is solved, so I'm closing this issue. Sorry for my mistake.
