### ISSUE TITLE
Wrong Auto Embedder Model used

### ISSUE THREAD

**Issue by rikimtasu** [ddPn08/rvc-webui#27]
Error displayed on webui:
```
Error: Traceback (most recent call last):
  File "D:\Software\RVC-webui\rvc-webui\modules\tabs\inference.py", line 107, in infer
    audio = model.single(
  File "D:\Software\RVC-webui\rvc-webui\modules\models.py", line 128, in single
    raise Exception(f"Not supported embedder: {embedder_model_name}")
Exception: Not supported embedder: hubert_base
```
Seem to happened after the japanese-hubert-base update. it should auto point to contentvec for older model

**Comment by ddPn08** [comment]
Probably fixed. Please update and check.

**Comment by rikimtasu** [comment]
> Probably fixed. Please update and check.

Thank you,seem to be fixed after the update. i will be closing this issue soon.
