### ISSUE TITLE
webui-user.bat実行時にエラーが出る

### ISSUE THREAD

**Issue by maaakigai** [ddPn08/rvc-webui#32]
![スクリーンショット (61)](https://user-images.githubusercontent.com/132727301/236595462-ea8a7f15-f743-409f-a3f0-aa7a17999f6d.png)
webui-user.bat実行時に画像のようなエラーが発生してしまいます。
解決策を教えていただけないでしょうか。
今のところgradioの再インストールとpipの更新を試してみましたが、だめでした。

**Comment by ddPn08** [comment]
修正しました。ご確認ください！

**Comment by maaakigai** [comment]
起動しましたが、エラーが発生してしまいました・・・設定等で誤っている場所があれば教えてい
ただけると嬉しいです！
同様のエラーが発生しているissueに対するアップデートが30分ほど前に行われていたのでそちらもupdate.batで適用してみましたが、変わらず同じエラーが発生してしまいました。
ログと設定は下記の画像のような感じです。
![-2スクリーンショット 2023-05-06 194327](https://user-images.githubusercontent.com/132727301/236619944-7dfa7f0c-8895-459a-8af3-f038d1b60165.png)
![-1スクリーンショット 2023-05-06 194258](https://user-images.githubusercontent.com/132727301/236619951-d9612c4f-ff31-433f-8bdc-ae72ec93bb6c.png)
![0スクリーンショット 2023-05-06 194156](https://user-images.githubusercontent.com/132727301/236619963-2b7358be-6524-416c-989d-dd0305cb6273.png)
![1スクリーンショット 2023-05-06 194119](https://user-images.githubusercontent.com/132727301/236619971-6cf02047-67b2-4248-bad7-a6374b463624.png)
![スクリーンショット 2023-05-06 194622](https://user-images.githubusercontent.com/132727301/236619977-18bf187b-29f7-4bff-833f-e224a0beef77.png)

**Comment by ddPn08** [comment]
こちらの実装ミスでした；先ほど修正いたしましたので、`update.bat`を実行して更新してから再度お試しください！

**Comment by maaakigai** [comment]
動きました！！対応本当にありがとうございます！！！！
