### ISSUE TITLE
Dataset glob について

### ISSUE THREAD

**Issue by hetima** [ddPn08/rvc-webui#5]
データセットフォルダの指定方法がglobパターンになって自由度は広がりましたが、`/**/*.wav` 以外のパターンを指定するケースはほぼないのではないかと思います。  
フォルダ指定に戻して、スクリプト側で `/**/*.wav` を付加する方が入力を簡便に済ませられて良いのではないかと思いますがいかがでしょうか。

**Comment by hetima** [comment]
と、書いているうちに変更入りました？！

**Comment by hetima** [comment]
というわけでcloseします

**Comment by ddPn08** [comment]
ちょうど変更していました；
とりあえずディレクトリとして存在する場合は後ろに`*.wav`をつけるようにしています。
