### ISSUE TITLE
RVC-webuiを起動しようとしたら以下のエラー文が出てきました

### ISSUE THREAD

**Issue by larneire** [ddPn08/rvc-webui#51]
エラー文
----------

Python.3.7_qbz5n2kfra8p0\python.exe"
venv "D:\rikiba\rvc-webui-main (1)\rvc-webui-main\venv\Scripts\Python.exe"
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Installing requirements
Traceback (most recent call last):
  File "launch.py", line 138, in <module>
    prepare_environment()
  File "launch.py", line 122, in prepare_environment
    errdesc=f"Couldn't install requirements",
  File "launch.py", line 36, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements.
Command: "D:\rikiba\rvc-webui-main (1)\rvc-webui-main\venv\Scripts\python.exe" -m pip install -r requirements.txt
Error code: 1
stdout: Collecting gradio==3.28.3
  Using cached gradio-3.28.3-py3-none-any.whl (17.3 MB)
Collecting tqdm==4.65.0
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)

stderr: ERROR: Could not find a version that satisfies the requirement numpy==1.23.5 (from -r requirements/main.txt (line 3)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
ERROR: No matching distribution found for numpy==1.23.5 (from -r requirements/main.txt (line 3))
WARNING: You are using pip version 20.1.1; however, version 23.1.2 is available.
You should consider upgrading via the 'D:\rikiba\rvc-webui-main (1)\rvc-webui-main\venv\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by nadare881** [comment]
python3.7であるのが原因そうです

**Comment by nadare881** [comment]
pythonを3.10にアップデートしたところ動きました
