### ISSUE TITLE
cant find Inferencing voice

### ISSUE THREAD

**Issue by Ab1077** [ddPn08/rvc-webui#59]
i put all the settings and used one-click training and i got: 
"added_IVF985_Flat_nprobe_1_IbrahemHefny_v2.index
All processes have been completed!"
but i couldnt find the model from the "Inferencing voice" slider even though i found the voice model in the log file
please help

**Comment by terracottahaniwa** [comment]
the following message seems to be from Retrieval-based-Voice-Conversion-WebUI.

["All processes have been completed!"](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/i18n/en_US.json#L9)

Retrieval-based-Voice-Conversion-WebUI and RVC-WebUI are two different projects. you can contact the repository of Retrieval-based-Voice-Conversion-WebUI that you using.

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues
