### ISSUE TITLE
モデルの読み込みが終わりません

### ISSUE THREAD

**Issue by M-rina1111** [ddPn08/rvc-webui#66]
環境は[README-ja.md](https://github.com/ddPn08/rvc-webui/blob/main/README-ja.md)に書いてある通りで試しました。
ｗebui-user.batを起動し、普通にhttp://127.0.0.1:7861 にアクセスも出来るのですが、Inferenceタブのモデル選択欄横のリサイクルマークを押しても、いつまでたってもモデルが読み込まれません。
もちろんrvc-webui\models\training\models\checkpoints\ にモデルは配置しました。

↓はバッチファイルの出力
``
Creating venv in directory C:\RVC\rvc-webui\venv using python "C:\Users\rinay\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\RVC\rvc-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: fae3965db830ed515d95096093811952d22b1870
Installing torch and torchvision
Installing requirements
2023-07-11 23:49:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-07-11 23:49:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-07-11 23:49:07 | INFO | faiss.loader | Loading faiss.
2023-07-11 23:49:07 | INFO | faiss.loader | Successfully loaded faiss.
C:\RVC\rvc-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Checkbox, please remove them: {'disabled': False}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
2023-07-11 23:57:27 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
``

↓いつまでも終わらないRVCの読み込み
![RVC](https://github.com/ddPn08/rvc-webui/assets/126447987/4da2a285-f494-4cf9-a74e-5bdac555571e)

**Comment by ddPn08** [comment]
3aed3783879637ad4d73ddb7b393857d674c2adc で修正されました。ご確認ください。
