### ISSUE TITLE
Guyz, plz help me it is saying me that C:\rvc-webui\tmp\ffmpeg.zip is not a zip file

### ISSUE THREAD

**Issue by Juranik** [ddPn08/rvc-webui#90]
```
Traceback (most recent call last):
  File "C:\rvc-webui\webui.py", line 26, in <module>
    webui()
  File "C:\rvc-webui\webui.py", line 16, in webui
    app = ui.create_ui()
  File "C:\rvc-webui\modules\ui.py", line 125, in create_ui
    preload()
  File "C:\rvc-webui\modules\core.py", line 156, in preload
    install_ffmpeg()
  File "C:\rvc-webui\modules\core.py", line 110, in install_ffmpeg
    shutil.unpack_archive(out, os.path.join(tmpdir, "ffmpeg"))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 1307, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 1201, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: C:\rvc-webui\tmp\ffmpeg.zip is not a zip file
```
Before I didnt have this problem, but now I reinstalled windows, and now I have this problem, I downloaded ffmpeg.zip from official site, and put it C: disk, but is it anyway won't work, pls help me

![Снимок экрана (1)](https://github.com/ddPn08/rvc-webui/assets/141658830/926f45f3-f524-4a1e-87a8-0c8f996ef511)
And why ffmpeg size 2KB?... it is very strange also xD

When I trying to open this zip file it is writing that file damaged

But when I insert ffmpeg on my own, when I run the bat file, it still replaces it with a damaged 2KB ffmpeg file.

Edited: I fixed this problem had to change some code, but now I have problem
``` Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")```

**Comment by ghost** [comment]
i have same problem.
but i fixed it.

[How to]
   core.py in the modules folder
   Edit install_ffmpeg() as follows
![ffmpeg_fix](https://github.com/ddPn08/rvc-webui/assets/12507805/e5ba7b33-956b-4b38-baa7-caa0023e54f6)

The broken link in the webURL originally called by this function is the cause of this problem.

**Comment by Juranik** [comment]
Ye, me too fixed it, but now it is writing ```ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")```, It doesn't seem to have happened before

**Comment by ghost** [comment]
1. go to [venv\Lib\site-packages\faiss]
2. Duplicate swigfaiss.py and rename it swigfaiss_avx2.py
![faiss_fix](https://github.com/ddPn08/rvc-webui/assets/12507805/fe7c0383-bb9a-4ef6-aeb7-b48471de692f)

When I tried to learn the RVC model after this, I got the error "avdevice-60.dll not found", so I copied the contents of the bin folder in ffmpeg.zip to rvc-webui\bin and this problem was solved.
![ffmpeg](https://github.com/ddPn08/rvc-webui/assets/12507805/d110744a-db49-47bf-9802-d5412542c725)

**Comment by Juranik** [comment]
BIG THANKS MAN, plz can u tell me which version gradio do u using? 
it is warning this okay? do u have the same in console?

```
C:\Users\Administrator\Desktop\rvc-webui-main\venv\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
  
  
C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\training.py:381: GradioUnusedKwargWarning: You have unused kwarg parameters in Checkbox, please remove them: {'disabled': False}
  fp16 = gr.Checkbox(
C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:16: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:20: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:24: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:116: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
  
```

**Comment by ghost** [comment]
> BIG THANKS MAN, plz can u tell me which version gradio do u using? it is warning this okay? do u have the same in console?
> 
> ```
> C:\Users\Administrator\Desktop\rvc-webui-main\venv\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
>   warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
>   
>   
> C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\training.py:381: GradioUnusedKwargWarning: You have unused kwarg parameters in Checkbox, please remove them: {'disabled': False}
>   fp16 = gr.Checkbox(
> C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:16: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
>   with gr.Row().style(equal_height=False):
> C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:20: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
>   with gr.Row().style(equal_height=False):
> C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:24: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
>   with gr.Row().style(equal_height=False):
> C:\Users\Administrator\Desktop\rvc-webui-main\modules\tabs\server.py:116: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
>   with gr.Row().style(equal_height=False):
>   
> ```

Yes,I have same warning messages.
No problem for training RVC models.

**Comment by Juranik** [comment]
Alright! Arigato!!! Good luck!😊
